#!/bin/sh
# this is to run a process in the conda environment provided in $1

source /etc/profile.d/conda.sh

# we're  not stacking the conda environment, who knows what this would cause
conda activate --no-stack ${JUPYTER_ENV:-/srv/jupyter}

exec $@

