#!/bin/sh

# take care of extensions, if any
EXTENSIONS=""

for EXT in $EXTENSIONS; do
echo "installing $EXT"
jupyter labextension install --no-build $EXT
done

echo "rebuild jupyter lab"
jupyter lab build
jupyter lab clean -y

